### ISSUE TITLE
Multiple Messages

### ISSUE THREAD

**Issue by nativecode2020** [hitgeek/simple-hl7#100]
Hi, I'm facing an issue when I send two messages consecutively using:

res.socket.write(data.message1)
res.socket.write(data.message2)

Only the first message is received. 

![image](https://github.com/user-attachments/assets/ebb3d087-55c2-458e-aa5e-c18273837aa6)

How can I send the messages one by one?

**Comment by hitgeek** [comment]
it looks like you are missing some sort of protocol that distinguishes the start and end of messages. 
Generally in HL7 that protocol is MLLP (https://www.covetus.com/blog/what-is-hl7-mllp-common-hl7-transports-applications-limitations) ... but that is just convention, it could be anything. 

So the answer to your question, is it depends on what the receiver is expecting.

**Comment by nativecode2020** [comment]
I am currently working on a task where I need to send two messages to a
device in sequence, one after the other. Could you kindly assist me

[image: image.png]
[image: image.png]

[image: image.png]
how can sent two messages one by one like image above

[image: image.png]

i just receive first message i need two message receive
