### ISSUE TITLE
Example Code Issues

### ISSUE THREAD

**Issue by MatthewVita** [hitgeek/simple-hl7#19]
Hi Bob,

I like the API and philosophies of this project. However, I'm finding that the `hl7.Message` code doesn't work correctly using your sample.

For instance if I run this code (copied verbatim from the sample):
```
var adt = new hl7.Message(
                    "EPIC",
                    "EPICADT",
                    "SMS",
                    "199912271408",
                    "CHARRIS",
                    ["ADT", "A04"] //This field has 2 components
                    //Keep adding fields
                );

/*
.addSegment() takes similiar syntax as Message constructor.
The first argument is segment name, and the rest of the arguments are added as fields.
*/

adt.addSegment("PID",
            "", //Blank field
            ["0493575", "", "", "2", "", "ID 1"], //Multiple components
            "454721",
            "",
            ["DOE", "JOHN", "", "", "", ""],
            "19480203"
            //Keep adding arguments to add more fields
        );

console.log(adt.toString());
```

I get:

```
matthew@matthew-VirtualBox ~/mock-emr-1 $ node server.js 
PID||0493575^^^2^^ID 1|454721||DOE^JOHN^^^^|1948020304
```

The header isn't attached and the value at the end is incorrect. Any ideas on why this is?

**Comment by hitgeek** [comment]
sorry for the confusion here. The documentation no longer works exactly the way it should. 
I think this is the issue you are hitting. [Issue 11](https://github.com/hitgeek/simple-hl7/issues/11)

The default segment separator had to be changed to \r to meet the HL7 spec.  Carriage returns don't play nice with console.log. The header segment is written to output, but without a newline (\n). So when the next segment is written out, it just overwrites on top of that previously segment. (That "04" you see at the end is the "A04" from the header) 😞  

anyway. there is a little blurb at the bottom of the readme that offers 2 options for working around this.
Here is the sample code that actually works. Notice how you can change the segmentSeperator to newline which prints nicely to console.log.

```
var hl7    = require('simple-hl7');

var adt = new hl7.Message(
                    "EPIC",
                    "EPICADT",
                    "SMS",
                    "199912271408",
                    "CHARRIS",
                    ["ADT", "A04"] //This field has 2 components
                    //Keep adding fields
                );

//******CHANGE THE SEGMENT SEPERATOR SO IT PRINTS NICELY TO console.log******
adt.header.delimiters.segmentSeperator = '\n'

/*
.addSegment() takes similiar syntax as Message constructor.
The first argument is segment name, and the rest of the arguments are added as fields.
*/

adt.addSegment("PID",
            "", //Blank field
            ["0493575", "", "", "2", "", "ID 1"], //Multiple components
            "454721",
            "",
            ["DOE", "JOHN", "", "", "", ""],
            "19480203"
            //Keep adding arguments to add more fields
        );

console.log(adt.toString());
```

**Comment by hitgeek** [comment]
[Update README](https://github.com/hitgeek/simple-hl7/commit/ce2a72e0dda5b7ff58ff5fe91bf1f3926d40e53d)

**Comment by MatthewVita** [comment]
Much appreciated :)
