### ISSUE TITLE
Server not receiving message through telnet

### ISSUE THREAD

**Issue by MQuach17** [hitgeek/simple-hl7#21]
Hi,

I'm trying to manually send a message over telnet on my local host but it is not logging the message to the console. 

The server is up and running fine but no logs.

**Comment by hitgeek** [comment]
HL7 over TCP uses MLP or MLLP Minimum Layer Protocol.
If you are using telnet, you will need to make sure you send the correct heading and trailing characters.

`<VT>
(hex 0x0b)	HL7 Message goes here	<FS>
(hex 0x1c)	<CR>
(hex 0x0d)`

The server will buffer the message until it gets the trailing termination characters.

If I had to guess, I think that might be your issue.

You can test this out by opening up simple-hl7 in your node_modules folder. put a `console.log(message)` after this line [https://github.com/hitgeek/simple-hl7/blob/master/lib/server/server/tcp-server.js#L28]( https://github.com/hitgeek/simple-hl7/blob/master/lib/server/server/tcp-server.js#L28)

**Comment by MQuach17** [comment]
added that console log after line 28, and added the heading and trailing characters, but in my app.js it never gets to the `tcpServer.on('msg'...` section 
```
tcpServer.on('msg',function(msg){
        console.log("here got message");
        console.log(msg.toString());
        var id= msg.getSegment('PID').getField(3)[0];
        console.log(id);
        fs.appendFile('hl7.log',msg.toString()+'\n',function(err){});
        conosle.log("here got message");
});
```

this is the output when I add those headers and trailers in the console. Looks like it is hitting that console.log(message); you suggested but not the function.

```HL7 server listening to port 8888
<VT> MSH|^~\&|EPIC|EPICADT|SMS|SMSADT|199912271408|CHARRIS|ADT^A04|1817457|D|2.5|
PID||0493575^^^2^ID 1|454721||DOE^JOHN^^^^|DOE^JOHN^^^^|19480203|M||B|254 MYSTREET AVE^^MYTOWN^OH^44123^USA||(216)123-4567|||M|NON|400003403~1129086|
NK1||ROE^MARIE^^^^|SPO||(216)123-4567||EC|||||||||||||||||||||||||||

<VT> MSH|^~\&|EPIC|EPICADT|SMS|SMSADT|199912271408|CHARRIS|ADT^A04|1817457|D|2.5|
PID||0493575^^^2^ID 1|454721||DOE^JOHN^^^^|DOE^JOHN^^^^|19480203|M||B|254 MYSTREET AVE^^MYTOWN^OH^44123^USA||(216)123-4567|||M|NON|400003403~1129086|
NK1||ROE^MARIE^^^^|SPO||(216)123-4567||EC|||||||||||||||||||||||||||
PV1||O|168 ~219~C~PMA^^^^^^^^^||||277^ALLEN MYLASTNAME^BONNIE^^^^|||||||||| ||2688684|||||||||||||||||||||||||199912271408||||||002376853 <FS> <CR>````

**Comment by hitgeek** [comment]
It looks like you are not sending the trailing characters necessary for the MLP that indicate the end of a message.

I don't know how you would send the File Separator character and Carriage Return via a command line telnet client. You could try copying them from text editor, or web page, and pasting them into the command line.

Is it a requirement to use telnet? If you use the tcp client in the library, it will handle the MLP stuff for you. see  `server.createTcpClient();` in the sample.

note the sample is outdated you actually need to do
```
var msg = parser.parse(hl7_string);

var tcpClient = server.createTcpClient();

tcpClient.connect('127.0.0.1', 8080);

tcpClient.send(msg, function(ack) {
  console.log(ack);
  tcpClient.close();
});
```

**Comment by MQuach17** [comment]
okay that worked, thank you.

telnet was not mandatory but I was using it to debug
