### ISSUE TITLE
Cannot read property 'getComponent' of undefined

### ISSUE THREAD

**Issue by harshalbagul-cse** [hitgeek/simple-hl7#25]
`var hl7=require('./node_modules/simple-hl7/lib/index.js');
var fs = require('fs');
var contents = fs.readFileSync('inMsg.txt', 'utf8');
var parser = new hl7.Parser();
var msg = parser.parse(contents);
console.log("Patient Name: "+msg.getSegment("PID").getComponent(5));`

inMsg.txt

MSH|^~\&|RIS||HIS||||ORU^R01|20120705082004|P|2.3.1
PID|1||HSNZ00655149||ESAH BINTI AMBAK||19430606|F||||||||||12IP00127841
PV1|1|I|I|||||^TIET/DR.AZD|||||||||||12IP00127841

I'm running this program, but unable to reads fields from msg.

**Comment by hitgeek** [comment]
try passing in some different values for `segmentSeperator ` https://github.com/hitgeek/simple-hl7/blob/master/lib/hl7/parser.js#L17.

technically `\r` is what the spec requires, but if you are manipulating the files in a text editor, this can sometimes get changed.

```
var parser = new hl7.Parser({segmentSeperator: '\r'}); //default
var parser = new hl7.Parser({segmentSeperator: '\r\n'}); 
var parser = new hl7.Parser({segmentSeperator: '\n'});
```

you want to use getField if there is only 1 component. 
are you can use getComponent with an index of 1.

```
var hl7 = require("simple-hl7")

var contents = `MSH|^~&|RIS||HIS||||ORU^R01|20120705082004|P|2.3.1
PID|1||HSNZ00655149||ESAH BINTI AMBAK||19430606|F||||||||||12IP00127841
PV1|1|I|I|||||^TIET/DR.AZD|||||||||||12IP00127841
`

var parser = new hl7.Parser({segmentSeperator: '\n'}); 
var msg = parser.parse(contents); 


console.log("Patient Name: "+msg.getSegment("PID").getField(5));
console.log("Patient Name 2: "+msg.getSegment("PID").getComponent(5, 1));
```
