### ISSUE TITLE
Uncaught errors on TcpClient

### ISSUE THREAD

**Issue by danapier** [hitgeek/simple-hl7#26]
var client = hl7.Server.createTcpClient('localhost', 7777);

If a connection attempt to target server fails I receive:

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED 127.0.0.1:7777
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

Can you add handlers for socket error/close?

**Comment by hitgeek** [comment]
https://github.com/hitgeek/simple-hl7/commit/9917a915416c2dc5014613aca332e433e5cc41c5

```
var client = hl7.Server.createTcpClient('localhost', 7777);
client.send(msg, function(err, ack) {
  //connection error should be caught and returned now
  if (err) console.log(err);
})
```
