### ISSUE TITLE
Processing batch messages

### ISSUE THREAD

**Issue by RyanQuey** [hitgeek/simple-hl7#28]
We need to handle and parse a series of several messages at once. We basically need to separate each of the messages before passing them to your Parser. (Separating them using something like `message.split(VT)`). I couldn't find an easy solution after looking through the code though. 

Is there a recommended way to handle batch messages with this lib? Or is it easiest to just override `app.start` with our own function, basing it off of what you already have? 

Thanks for this project; it is just what we're looking for as we're starting to handle hl7 requests with our server.

**Comment by hitgeek** [comment]
what if the lib provided the raw data as part of the req?
so you can manually handle this special batch parsing via middleware, instead of hacking your own `start` method?

for example

```

app.use(function(req, res, next) {
//here you will set for own "messages" property on req
req.messages = [];
req.raw.split(VT).forEach(function(x) {
  req.messages.push(parser.parse(x));
});
next();
})

//middleware further down the pipeline 
app.use(function(req, res, next) {
  req.messages.forEach(function(msg) {
    //do stuff with msg
   })
  res.end();
})

```

**Comment by hitgeek** [comment]
i've never had to deal with this scenario, so I don't have any features built in to handle it.

let me know if you like this idea, or have another idea, and I will incorporate it.

**Comment by RyanQuey** [comment]
@hitgeek Something like that could work. I think the main issue I ran into was that there is a conditional in the start function (`if (message.substring(message.length - 2, message.length == FS + CR) {...)`) that made it so bulk messages wouldn't go through.

Especially with different formats for bulk messages, having a way to access that even when this doesn't work would be great.

**Comment by RyanQuey** [comment]
@hitgeek Actually, ignore that last comment. The particular batch messages I'm getting end up fitting the same format (ie, they still fall within the conditional, acting as if they end in FS + CR)...although I'm not sure how, since I'm pretty sure the data ends in only a CR). 

However, perhaps having the format stay flexible would be helpful regardless, in case other batch messages don't conform to that? 

If there's something you want a PR for too, let me know

**Comment by hitgeek** [comment]
is the client expecting 1 response for all messages in the batch, or an individual response for each message?

in this code block (https://github.com/hitgeek/simple-hl7/blob/master/lib/server/tcp-server.js#L58), the server creates the 1 HL7 message, 1 ACK message and passes these into the middleware stack.

in your case, would you expect a batch of 3 messages to result in 3 passes through the middleware stack, or just 1 one time?

**Comment by RyanQuey** [comment]
@hitgeek I would need to ask the client to be definitive, and they're on break. But, the example batch I got was thousands of messages, which was for one day of data, so if that's any indicator, then just one ACK for all. 

Maybe the best way would be to be able to pass in an options arg when starting the server (eg, `app.start(7777, {batch: true})`), which would put the raw message on the `req` object, and ignore the  check in [line 57](https://github.com/hitgeek/simple-hl7/blob/master/lib/server/tcp-server.js#L57).  Maybe would want to skip parsing at all, in case that could raise errors for some batch formats? 

With that I could get the ack, set the msg, etc in the middleware by requiring various modules from your lib. 

Then users call `app.end` multiple times, if it could an `ack` as an arg, which would override `res.ack` (something like `this.end = function(ackToSend = ack) {...`. Or they could just send once, depending on what the client is expecting, but it would be flexible. 

Does that sound reasonable?

**Comment by hitgeek** [comment]
you may be better off not using the built in tcp server, and handling the tcp manually, because the build in server assumes 1 message per req/res. fighting against that might be an uphill battle.

you could still use the parser and message builder parts of the library.

you might be able to modify the v1 version of the tcp server to meet your needs. https://github.com/hitgeek/simple-hl7/blob/v1/lib/server/server/tcp-server.js
this version emitted events for each message, instead of using a connect like middleware pipeline.

I don't know enough about the requirements to add in support for this type of batch message handling myself, but I'd be open to a PR that built in generalized support for it, without over complicating things.

**Comment by RyanQuey** [comment]
Sounds good, just made a pr, let me know what you think. Just kept it simple and flexible.
