### ISSUE TITLE
Tcp Client issue.

### ISSUE THREAD

**Issue by yusbel80** [hitgeek/simple-hl7#33]
Needs to modify

`
TcpClient.prototype.close = function() {
    var self = this;
    if (self.client) {
        self.client.end();
        self.awaitingResponse = false;
        delete self.client;
    }
}`

update awaitingResponse to 'false' in order to proceed to next send process.

**Comment by hitgeek** [comment]
i think your right, do you want to submit a Pull Request?

**Comment by yusbel80** [comment]
Ill let you do it. I just noticed this happening during a connection error or timeout, would not allow future send request.

Great work on this package tho, I am currently using it at work.

**Comment by attrib** [comment]
while checking some stuff, noticed this got fixed, so could be closed?
