### ISSUE TITLE
Question: Typescript definition file location

### ISSUE THREAD

**Issue by nootn** [hitgeek/simple-hl7#39]
I am planning to use this library in a Typescript project but I will need to generate definitions which I am happy to do.

My question is though, if I do that would you like those as a http://definitelytyped.org/ commit so they are not included in this repo, or direct in this repo and do a pull request?

**Comment by hitgeek** [comment]
Thanks for contribution. I’m not to familiar with the typescript eco-system. Whatever is the preferred method of managing the definitions, I will go along with that. If you do a pull request I will merge it and publish to npm.

**Comment by nootn** [comment]
OK thanks, I am just checking the official documentation for best practices so I will get my head around that more before deciding!
http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by nootn** [comment]
Looks like contributing them to the @types org on NPM is the preferred approach since your library is written in JS not TS - so I will do that, and close this issue.  Thanks very much!

**Comment by bradtaniguchi** [comment]
I'm currently looking into hl7 options for a TypeScript project. @nootn did you ever start/look into building more types for this library, or did you end up taking another route?

Otherwise I'm building my own types around the current code just to get by :)

**Comment by DanielFontenot** [comment]
I don't see anything published as @types for this library. @nootn @bradtaniguchi did either of you ever complete this endeavor and upload? Don't want to reinvent the wheel obviously

**Comment by bradtaniguchi** [comment]
> I don't see anything published as @types for this library. @nootn @bradtaniguchi did either of you ever complete this endeavor and upload? Don't want to reinvent the wheel obviously

I build enough to get by with what I was doing and didn't continue. Here's what I have **as-is**. It clearly needs a lot of work but is my starting point:
```ts
/**
 * This is a WIP
 */
declare module 'simple-hl7' {
  export class Message {
    constructor(...args: Array<string | Array<string>>);

    addSegment(...args: Array<string | Array<string>>): any;

    getSegment(segment: string): any; // TODO: probably its own data-type

    /**
     * Returns the current message as a string
     */
    log(): string;
  }

  export class Field {
    constructor(...args: Array<string>);
  }

  export class Parser {
    constructor();
    /**
     * Takes the hl7 string and returns a message
     */
    parse(str: string): Message;
  }
}

```

**disclaimer** its been a while since I looked at the rest of the code so this might even be wrong, but last I checked its working with our other code 👍🏼

**Comment by DanielFontenot** [comment]
Thank you Brad! Nice to know I can get along with this simple implementation, it is working for me too. If I expand upon it, I will share any improvements.
