### ISSUE TITLE
Ack back to device  

### ISSUE THREAD

**Issue by kuzmic** [hitgeek/simple-hl7#41]
Hello, im work with your code, but i have a problem. I  have device connected to my server with your code , im recieving messages  (works good), but one same  message with same data  are received  in loop because your code not sending back ack, can you help me how can I sent correct ack  back  when message is received

in my opinion there is a bug in ack

******message received*****
MSH|^~\&|^URI2P-1.3^L||||20200605195237||OUL^R22^OUL_R22|6104460-7502878|P|2.7|0||NE|AL||UNICODE UTF-8

******sending ack*****
MSH|^~\&|||^URI2P-1.3^L||20200605195307||ACK|ACK20200605195307|P|2.3
MSA|AA|6104460-7502878

**Comment by hitgeek** [comment]
are you calling res.end() ? that sends the ack. if that isn't the issue, could you share some sample code that you are using?

**Comment by kuzmic** [comment]
yes i calling res.end(), what I tried and what I came for my device still sends HL7 a message in the loop because the server seems to confirm it badly, I don't know if the ACK message is correct...
i used this code : https://www.npmjs.com/package/simple-hl7 without client ... I'm new to HL7, so I look, and as I look, you look more experienced than I do.

**Comment by hitgeek** [comment]
are you able to confirm if the device is receiving the ack? 

maybe try changing the version of the ack to 2.7?

you may have to look into the documentation of the device to see what type of ack it is expecting.

if you need to customize the ack, you can do so via the res.ack object. You can add segments, change segments, etc.
