### ISSUE TITLE
How to re-parse a message?

### ISSUE THREAD

**Issue by bluepuma77** [hitgeek/simple-hl7#45]
During testing I found that incorrect formated messages with NL \n character are parsed with segment names like "\nPV1" and therefore those can not be found. Is there a best way to re-parse a message?

Like pseudo-code
```
if (String(req.msg).indexOf('\n')>-1) {
  req.msg = parse( String(req.msg).replace(/\n/g, "\r") );
}
```

**Comment by hitgeek** [comment]
from my understanding the segment separator must be a carriage return, \r. so if the message you are parsing uses \n, then the message is invalid. 

but you can still override this in the parser via `var parser = new parser({ segmentSeperator: '\r\n' })`. https://github.com/hitgeek/simple-hl7/blob/master/lib/hl7/parser.js#L17

You can then use this custom parser in your server here https://github.com/hitgeek/simple-hl7/blob/master/lib/server/tcp-server.js#L23
