### ISSUE TITLE
Repeatable fields - Support

### ISSUE THREAD

**Issue by JasonWeh** [hitgeek/simple-hl7#48]
segment.getComponent function does not seem to support repeatable fields
below is updated to function so can access value for repeatable fields
```
segment.prototype.getComponent = function(fieldIndex, componentIndex, subComponentIndex, repeatIndex) {
  if (this.fields.length >= fieldIndex) {
    var components;
    if (repeatIndex) {
      components = this.fields[fieldIndex - 1].value[repeatIndex - 1].value[0];
    } else {
      components = this.fields[fieldIndex - 1].value[0];
    }
    if (components.length >= componentIndex) {
      var component = components[componentIndex - 1]
      if (subComponentIndex) {
        if (component.value[0].length >= subComponentIndex) {
          return component.value[0][subComponentIndex - 1].toString(delimiters)
        }
        return "";
      }
      return component.toString(delimiters);
    }
    return "";
  }
  return "";
}
```

Unsure how can create hl7 repeatable fields with array syntax.  Any input would be appreciated.

Regards

Jason Weh

**Comment by hitgeek** [comment]
you can create repeating fields like this.  https://github.com/hitgeek/simple-hl7/blob/master/examples/message.js#L29

**Comment by hitgeek** [comment]
to get repeating fields, you would have to use `.getField()` which has a repeatIndex parameters  `pid.getField(7, 1)`

https://github.com/hitgeek/simple-hl7/blob/master/lib/hl7/segment.js#L75
