### ISSUE TITLE
High message volume leads to dropped ACKs/messages

### ISSUE THREAD

**Issue by rholzum-formfast** [hitgeek/simple-hl7#51]
We tried stress testing this library, and found under high volume load, some ACK's wern't being sent.

We think the issue originates from the socket.on('data' function below.  If the messages occur often enough, multiple messages could be in the 'data' parameter, but there is no for loop checking for them.

![image](https://user-images.githubusercontent.com/18537691/107972940-31f89500-6f7a-11eb-825d-b78d327c0d37.png)

As an example, during debugging, here's what the data parameter held -- showing there's multiple messages in there.

`MSH|^~\\&|AccMgr|1|||20050110045504||ADT^A04|599102|P|2.3|||\r\nPID|1||MMBD00003362A||DUCK^DHAANZQCZE^D||19241010|M||1|111 NKYBHWSFYI 1|8885551212^PT^PT^test+dduck@website.com|ST^^FOWL^CA^999990000^^M|1|8885551212^PT^PT^test+dduck@website.com||1|2||40007716^^^AccMgr^VN^1|123121234|||||||||||NO\r MSH|^~\\&|AccMgr|1|||20050110045504||ADT^A04|599102|P|2.3|||\r\nPID|1||MMBD00003362A||DUCK^DNJPAZEFZY^D||19241010|M||1|111 SWEMRKWVPD 1|8885551212^PT^PT^test+dduck@website.com|ST^^FOW…ZCPJOZDSU 1|8885551212^PT^PT^test+dduck@website.com|ST^^FOWL^CA^999990000^^M|1|8885551212^PT^PT^test+dduck@website.com||1|2||40007716^^^AccMgr^VN^1|123121234|||||||||||NO\r MSH|^~\\&|AccMgr|1|||20050110045504||ADT^A04|599102|P|2.3|||\r\nPID|1||MMBD00003362A||DUCK^UKADOICQSQ^D||19241010|M||1|111 QRGAXKCVKC 1|8885551212^PT^PT^test+dduck@interlacehealth.com|ST^^FOWL^CA^999990000^^M|1|8885551212^PT^PT^test+dduck@website.com||1|2||40007716^^^AccMgr^VN^1|123121234|||||||||||NO\r'`

**Comment by hitgeek** [comment]
2 questions

is your client waiting for an ACKs before sending the next message? is the server receiving messages from multiple different clients?

in my experience, the most common pattern in TCP HL7 is that a server only handles messages from only 1 client, and that 1 client waits until receiving an ACK before sending the next message. In that scenario, it doesn't seem possible to have 2 messages in the `data` at the same time (unless something weird is going on with the underlying node socket stuff that I have not experienced before)

however, if you are receiving messages from multiple clients, or 1 client is sending multiple messages, even low volume could cause the behavior you are experiencing if messages are sent at the same time. And the library doesn't really have anything to handle that. (other then maybe using file based HL7)

if there is only 1 client, and the client is waiting for ACKs before sending the next message, and you are still seeing this behavior, could you maybe share a test or sample code or something and I can take a look. 

Or if you have any ideas and want to submit a PR, that is OK as well.
