### ISSUE TITLE
getField on headers

### ISSUE THREAD

**Issue by jssuttles** [hitgeek/simple-hl7#55]
Version 2.2.1
When using message.header.getField(6), it gets the wrong field.
For example with the following MSH segment:

MSH|^~\&|PLACE||PLACE|PLACE2|201612050742|SOMETHING|ORM^O01|ORM|P|2.4|||||||||

It returns SOMETHING instead of PLACE2.

**Comment by hitgeek** [comment]
i chose to implement the "fields" for the MSH as starting after the encoding characters, not including them. so Field 1 is the first real data field (PLACE in your example), not the "|" field separator after MSH.

using that indexing PLACE2 is field 4, and SOMETHING is field 6.

**Comment by jssuttles** [comment]
Alright. But technically, MSH 1 is the field separator.
https://hl7-definition.caristix.com/v2/HL7v2.5.1/Fields/MSH.1
I ended up implementing a weird field number - 2 system to compensate.

**Comment by hitgeek** [comment]
i agree with your assesment so I'm going to change this in the next major version. along with this other issue. https://github.com/hitgeek/simple-hl7/issues/56

**Comment by jssuttles** [comment]
I don't know if this has been implemented yet

**Comment by MKmedicalvalues** [comment]
No, it is not implemented yet. 
Last release was late 2018. 
I could create a pull request if @hitgeek is still maintaining this repo and intends to release further versions.

**Comment by hitgeek** [comment]
I think I updated this in v4, which is availible on npm via @next tag
