### ISSUE TITLE
Better documentation for changing the encoding

### ISSUE THREAD

**Issue by aligator** [hitgeek/simple-hl7#57]
Hi,
I needed some time to find out how to pass another encoding to the tcp server:
```
app.start(1234, 'latin-1');
```
It would be nice to have this documented somewhere :-)

**Comment by hitgeek** [comment]
https://github.com/hitgeek/simple-hl7/commit/67b30c46fa7c158211223e911156bdb16c24c94a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
