### ISSUE TITLE
TCP Setup for HL7 Raw Data

### ISSUE THREAD

**Issue by bernardthegreat** [hitgeek/simple-hl7#60]
Hi thanks for your hardwork on creation and support on this. I just want to ask if I can get the actual Raw Data that the client sent to me. I tried using the raw object but it's incomplete. 

Here is the sample of the HL7 Message from our Third Party Provider:

MSH|^~\&|NovaRAD|TEST Facility|Novaris|PHI-UE|20210728173635.0000+08:00||ORU^R01|cXNktbDBKIUnMEd1pn8M|P|2.3
PID|1||2100324233||TEST^SAMPLE^INDIVIDUAL||19740605000000.0000+08:00|F||||||||||30911
PV1|1|O|^^^^^^^^OPD-CHA||||15^LASTNAME, DOCTOR^DOCTOR FIRSTNAME|21^PHYSICIAN^RESIDENT
ORC|RE|XR00170706|49145||||^^30^20210728110600.0000+08:00^20210728113600.0000+08:00||20210728112723.0000+08:00|3^null^SYSTEM||21^PHYSICIAN^RESIDENT
OBR|1|XR00170706|49145||||20210728144320.0000+08:00|||||||||||XR00170706_7917||||||CR|F||^^30^20210728110600.0000+08:00^20210728113600.0000+08:00|||||20^Ramirez, MD, FPCR, FUSP^R Rally|||8^Ko, MD (Resident)^Erick Rowel|||||||||7917^ESOPHAGOGRAM/BARIUM SWALLOW (GE)^^^ESOPHAGOGRAM/BARIUM SWALLOW (GE)
OBX|1|TX|^49175.7230.Report Text||Clinical data: GERD (2018); Dysphagia to solids and liquids~~Plain film (AP, lateral, oblique) shows no mass lesion of the esophagus. An air-fluid level is seen at the thoracic portion of the esophagus, T4 level, with dilatation of the cervical and proximal thoracic esophagus.~~Real time fluoroscopy shows transit of barium through the entire length of the esophagus, from the oropharynx, down to the stomach. The esophagus is markedly dilated and tortuous which measures, 5.0 cm (cricopharyngeal area, C6 level), 6.0 cm (arch of aorta, T5 level), and 5.0 cm (diaphragm, T10 level). There is abnormal pooling of contrast media seen at the mid- to distal esophagus. Mild mucosal irregularities at the mid-thoracic esophagus, level of the arch of aorta is noted. Central longitudinal lucency bounded by barium on both sides (tram track appearance) is seen at the mid- esophageal area. There is a delayed transit of contrast media from the narrowed distal esophagus to the stomach due to an area of constriction at the gastro-esophageal junction (bird's beak appearance). ~ Delayed film (LPO) shows contrast media within the distal esophagus, stomach and duodenum.~~No other findings of note. ~ Impression:  Achalasia. Suggestive mucosal irregularities at the mid-thoracic esophagus, may represent areas of inflammation. Direct visualization via endoscopy is suggested for further evaluation.~  ~|||||||||||||
OBX|2|RP|334855903.AccessURL||||http://10.107.3.214/NovaWeb/WebViewer/Account/ValidateUserFromUrl?key=01Y6PcGGeqvtmtiTfQfWzzZAZfmLuyzTO3wKA8Ox.BdpAby6AcMPSMs-rEmRYu0eVvMhGxh9j.sf8TKSW4fg3zrBJt.zZSRKKjnyP6vjJxB.o68aSQUd1NUU

However I only received this upon transmission:

OBR|1|XR00170706|49145||||20210728144320.0000+08:00|||||||||||XR00170706_7917||||||CR|F||^^30^20210728110600.0000+08:00^20210728113600.0000+08:00|||||20^Ramirez, MD, FPCR, FUSP^R Rally|||8^Ko, MD (Resident)^EriOBX|1|TX|^49175.7230.Report Text||Clinical data: GERD (2018); Dysphagia to solids and liquids~~Plain film (AP, lateral, oblique) shows no mass lesion of the esophagus. An air-fluid level is seen at the thoracic portion of the esophagus, T4 level, with dilatation of the cervical and proximal thoracic esophagus.~~Real time fluoroscopy shows transit of barium through the entire length of the esophagus, from the oropharynx, down to the stomach. The esophagus is markedly dilated and tortuous which measures, 5.0 cm (cricopharyngeal area, C6 level), 6.0 cm (arch of aorta, T5 level), and 5.0 cm (diaphragm, T10 level). There is abnormal pooling of contrast media seen at the mid- to distal esophagus. Mild mucosal irregularities at the mid-thoracic esophagus, level of the arch of aorta is noted. Central longitudinal lucency bounded by barium on both sides (tram track appearance) is seen at the mid- esophageal area. There is a delayed transit of contrast media from the narrowed distal esophagus to the stomach due to an area of constriction at the gastro-esophageal junction (bird's beak appearance). ~ Delayed film (LPO) shows contrast media within the distal esophagus, stomach and duodenum.~~No other findings of note. ~ Impression:  Achalasia. SuggestivOBX|2|RP|334855903.AccessURL||||http://10.107.3.214/NovaWeb/WebViewer/Account/ValidateUserFromUrl?key=01Y6PcGGeqvtmtiTfQfWzzZAZfmLuyzTO3wKA8Ox.BdpAby6AcMPSMs-rEmRYu0eVvMhGxh9j.sf8TKSW4fg3zrBJt.zZSRKKjnyP6vjJxB.o68aSQUd1NUU∟

Thank you, keep safe and have a good day.

**Comment by hitgeek** [comment]
To identify the received data are you logging to the console? I've seen similar behavior when logging to console due to the way carriage returns used in HL7 don't work well with console output. If you are logging to console, try using req.msg.log(), instead of .toString(), as this will use line feeds with carriage returns in the output, which normally prints to the console better. Or try writing your received data out to a txt file instead of the console. 

If you are still having trouble and need to troubleshoot with the underlying node socket API... this is where you would start https://github.com/hitgeek/simple-hl7/blob/master/lib/server/tcp-server.js#L59.

**Comment by bernard-uerm** [comment]
Thank you so much ! You're a lifesaver ! 

> To identify the received data are you logging to the console? I've seen similar behavior when logging to console due to the way carriage returns used in HL7 don't work well with console output. If you are logging to console, try using req.msg.log(), instead of .toString(), as this will use line feeds with carriage returns in the output, which normally prints to the console better. Or try writing your received data out to a txt file instead of the console.
> 
> If you are still having trouble and need to troubleshoot with the underlying node socket API... this is where you would start https://github.com/hitgeek/simple-hl7/blob/master/lib/server/tcp-server.js#L59.

Thank you so much ! You're a lifesaver !
