### ISSUE TITLE
not able to append 0d1c0d at MSA end in response ack

### ISSUE THREAD

**Issue by soniharshil54** [hitgeek/simple-hl7#84]
we need to append the specific hex values at the end of MSA segment of the response ack for the client to parse the response message. we have tried doing it by adding a new field in MSA segment with the values that we need to append to it.

```
const msa = res.ack.getSegment('MSA');
msa.addField(`${String.fromCharCode(13)}${String.fromCharCode(28)}${String.fromCharCode(13)}`);`
```        

here 13 is the charactercode for hex value 0D. and 28 is the character code for hex value 28.
reference: [hex table](https://www.freecodecamp.org/news/ascii-table-hex-to-ascii-value-character-code-chart-2/)

but what we are getting at the client side is `0D1C1C0D` instead of `0D1C0D` in the newly added MSA field.

We have the software working for several hl7 client softwares which maybe don't need `0D1C0D` appended at the end.
but we are having difficulties integrating our software for a specific client which needs to have `0D1C0D` at the end of the response ack.

**Comment by hitgeek** [comment]
The MLLP wrapper around the tcp server response is handled automatically here. https://github.com/hitgeek/simple-hl7/blob/master/lib/server/tcp-server.js#L48 .... adding a field to the response would not be the way to adjust the response message wrapper. 

i've never heard of a TCP HL7 server not using standard MLLP protocol... but if you wanted to use a different message wrapper, you could monkey patch the `end` method of the `res` object something like

` res.end = () => this.socket.write( START_CHARS + (this.ack).toString() + END_CHARS )`

or not use the build in `end` method at all, and handle the response sending manually. 
```
app.use(function(req, res, next) {
  res.socket.write(WHATEVER_RESPONSE_YOU_WANT);
})

```
