### ISSUE TITLE
tcpClient on error

### ISSUE THREAD

**Issue by cmacrae2016** [hitgeek/simple-hl7#9]
Hi there, 

I am unable to catch the TCP error when I send to a port that isn't listening. Can you please have a look?

Cheers,

**Comment by hitgeek** [comment]
after you call connect on tcpClient, the underlying node tcp object is inside the tcpClient in a property called "client". try to add a handler to the error event of this. see below

    var server = hl7.Server;

    var tcpClient = server.createTcpClient();

    tcpClient.connect('127.0.0.1', 9696);
    
    tcpClient.client.on('error', function(err) { console.log(err); });

I tested this a little and it seemed like once I added a handler for this event, the exception wasn't thrown anymore.

**Comment by hitgeek** [comment]
see commit [8616c4e](https://github.com/hitgeek/simple-hl7/commit/8616c4e1fd8ee7d5c33d03783e0295b893a28bcb) for new test.
