### ISSUE TITLE
Error: ‘req’ object undefined when using Simple-HL7 library in Node.js

### ISSUE THREAD

**Issue by rohitbaisane** [hitgeek/simple-hl7#92]
**Issue Description:**
I encountered an error while using the Simple-HL7 library in Node.js. When trying to set a property on the req object within the attachBrokerHL7Process middleware function, I receive a TypeError stating “Cannot set properties of undefined 
(setting ‘broker’)“.

**code:**
const hl7 = require('simple-hl7');

// Define the attachBrokerHL7Process middleware function
const attachBrokerHL7Process = (req, res, next) => {
  try {
    req.broker = "RABBITMQ";
  } catch (e) {
    req.broker = null;
  }
  next();
};

const app = hl7.tcp();

// Use the attachBrokerHL7Process middleware function
app.use(attachBrokerHL7Process);

// Additional code for handling HL7 messages

// Start the server
app.start(1234);

**Error stack:**
TypeError: Cannot set properties of undefined (setting 'broker')
    at attachBrokerHL7Process (/usr/src/app/middleware/attachBrokerHL7Process.js:19:16)
    at call (/usr/src/app/node_modules/simple-hl7/lib/connect/proto.js:46:7)
    at next (/usr/src/app/node_modules/simple-hl7/lib/connect/proto.js:29:5)
    at Function.proto._handle (/usr/src/app/node_modules/simple-hl7/lib/connect/proto.js:33:3)
    at TcpServer.app [as handler] (/usr/src/app/node_modules/simple-hl7/lib/connect/tcp.js:12:9)
    at Socket.<anonymous> (/usr/src/app/node_modules/simple-hl7/lib/server/tcp-server.js:81:12)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    
  **Additional Notes:
Please note that the line numbers in the error stack trace provided are not accurate and should be ignored.**

**Comment by soniharshil54** [comment]
@rohitbaisane  +1
I have been facing the same issue.
This issue occurs randomly and is not consistently reproducible.

**Comment by hitgeek** [comment]
thanks for bringing this up. I think this is due to some incorrect error handling. I think this fixes it. https://github.com/hitgeek/simple-hl7/commit/d4c08f2aa5e96bbde09e64876abdb2508455b7e8 

are you able to upgrade to v4, its available via npm install simple-hl7@next ?

**Comment by rohitbaisane** [comment]
@hitgeek 
How to replicate this scenario of getting request object as a  undefined?

**Comment by hitgeek** [comment]
I believe this would be triggered by this code path, https://github.com/hitgeek/simple-hl7/blob/master/lib/server/tcp-server.js#L77  (some sort of error in the underlying socket)


I replicated this by simulating a socket error (https://github.com/hitgeek/simple-hl7/commit/d4c08f2aa5e96bbde09e64876abdb2508455b7e8#diff-c22a1247de90509303e2dbe6a3d0d79bfa470a644f92fa01c79e73325283845cR145)


presuemably an unhandled error in the parser could also cause this, and end up in this code path
or this code path https://github.com/hitgeek/simple-hl7/blob/master/lib/server/tcp-server.js#L71

**Comment by rohitbaisane** [comment]
This issue is resolved.
