### ISSUE TITLE
keep connection open 

### ISSUE THREAD

**Issue by nativecode2020** [hitgeek/simple-hl7#97]
hi have problem in this libarary 
when i need client keep open connection when make connect 
like mirth connect
 <keepConnectionOpen>true</keepConnectionOpen>

**Comment by hitgeek** [comment]
you should be able to use `keepalive: true ` in the client options. 
https://github.com/hitgeek/simple-hl7/blob/master/examples/tcp.js#L51

https://github.com/hitgeek/simple-hl7/blob/master/lib/client/tcp-client.js#L36
