### ISSUE TITLE
respond ack not work

### ISSUE THREAD

**Issue by nativecode2020** [hitgeek/simple-hl7#99]
Hi,i need send ACK^R01 to CL900 analyzer but not recive it 

   var dsr2 = new hl7.Message("","","","","20241018110131", "", "ACK^R01", "1", "P", "2.3.1","","","","0","","ASCII","","","");

    // Add MSA (Message Acknowledgment) Segment
    dsr2.addSegment(
      "MSA",
      "AA",  // Application Accept
      "1",   // Message Control ID
      "Message accepted", // MSA-3 message text
      "",    // Optional fields
      "",    // Optional fields
      "0",
      ""    // Optional fields
    );
    //console.log(dsr2.log());
    res.ack = dsr2;
    res.end()

![image](https://github.com/user-attachments/assets/2938ae79-78ba-4e42-ad5c-cd2a0b656ef0)

**Comment by hitgeek** [comment]
sorry, I won't be able to assist in troubleshooting any issues you have with a particular device. I confirmed setting a custom ACK works, so I don't believe the issue is related to this library. 
you may want to confirm if this device expects MLLP (Minimum Lower Layer Protocol)

**Comment by nativecode2020** [comment]
Ok, thank you.
